spring:
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.252.42:3306/teacher_training?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 3ADFKdPY@8G!cs@D
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8901
  servlet:
    encoding:
      force: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.training.core.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      logic-delete-field: is_del
      logic-delete-value: 1
      logic-not-delete-value: 0
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

